# -*- coding: utf-8 -*-
"""Media/Moda/Mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mKa1mJBP7K6bY8Wt2EBxs4fdXfuH8ZU

#Média
"""

import numpy as np

dados = [2,4,6,8,10]
media = np.mean(dados)

print("Média: ", media)

import statistics as st

dados = [2,4,6,8,10]
media = st.mean(dados)

print("Média: ", media)

type(media)

"""#Moda"""

import statistics as st

dados = [2,2,2,3,5,4,3,3,6,5,8,2,2,3,3,2,2,4,3,6,2,3,2,3,3,3,2]
moda= st.mode(dados)

print("Moda: ", moda)

"""#Mediana"""

import numpy as np

dados = [2,4,6,8,10]
mediana = np.median(dados)

print("Mediana:", mediana)

"""#Exemplo 01"""

import statistics as st

salarios = [1200, 1200, 1200, 1800, 2800,3000, 2100, 45000]

media = st.mean(salarios)
mediana = st.median(salarios)
moda = st.mode(salarios)
variancia = st.variance(salarios)
desvio_padrao = st.stdev(salarios)

print("Média:", media)
print("Mediana: ", mediana)
print("Moda: ", moda)
print("Variancia: ", variancia)
print("Desvio padrao: ", desvio_padrao)

"""#Desvio Padrão

"""

import numpy as np

dados = [1,1,1,1,1]
desvio_padrao = np.std(dados)

print("Desvio Padrão: ", desvio_padrao)

import statistics as st

dados = [1,1,1,1,1]
desvio_padrao = st.stdev(dados)

print("Desvio Padrão: ", desvio_padrao)

"""#Variância"""

#Variancia Amostral
import numpy as np
dados = [2,4,6,8,10]
variancia = np.var(dados, ddof=1)

print("Variancia: ", variancia)

#Variancia Amostral
import statistics as st

dados = [2,2,2,2,2,2.1]
variancia = st.variance(dados)

print("Variancia: ", variancia)

#Variancia Populacional
import numpy as np

dados= [2,4,6,8,10]
variancia = np.var(dados)

print("Variancia: ", variancia)

#Variancia Populacional
import statistics as st

dados= [2,4,6,8,10]
variancia = st.pvariance(dados)

print("Variancia: ", variancia)

"""#Correlação"""

import numpy as np
import pandas as pd

dados = pd.DataFrame({'horas_estudo' : [1,2,3,4,5],
                      'nota' : [3,5,8,9,9.5]})
dados #Exibe DataFrame

correlacao = np.corrcoef(dados['horas_estudo'], dados['nota'])
print("Correlação: ", correlacao)

"""#Gráfico"""

import matplotlib.pyplot as plt

plt.scatter(dados['horas_estudo'], dados['nota'])
plt.title('Horas de Estudo x Nota')
plt.xlabel('Horas de Estudo')
plt.ylabel('Nota')
plt.show()